name: Build Plugin
on:
  push:
    branches:
      - master
      - test-ru
    tags:
      - v*
  pull_request:

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make check-style
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make dist DEFAULT_GOOS=linux DEFAULT_GOARCH=amd64 MM_SERVICESETTINGS_ENABLEDEVELOPER=true
      - uses: actions/upload-artifact@v3
        with:
          name: mattermost-plugin-ai.tar.gz
          path: dist/*.tar.gz
  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs:
      - build
      - test
      - check-style
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: mattermost-plugin-ai.tar.gz
          path: dist
      - run: |
          printf "## Commits\n" > release-notes.md
          git log --pretty='format:- %h %s' --abbrev-commit --no-decorate --no-color $(git describe --tags --abbrev=0 $(git describe --tags --abbrev=0)^)..HEAD >> release-notes.md
      - run: gh release create "$GITHUB_REF_NAME" --title "$GITHUB_REF_NAME" --notes-file release-notes.md  dist/*.tar.gz
        env:
          GH_TOKEN: ${{github.token}}
